name: 'Run misspell with reviewdog'
description: '🐶 Run misspell with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
  locale:
    description: '-locale flag of misspell. (US/UK)'
    default: ''
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  ignore:
    description: 'Comma-separated words to ignore'
    default: ''
  path:
    description: "Base directory to run misspell. Same as `[path]` of `find` command."
    default: '.'
  pattern:
    description: "File patterns of target files. Same as `-name [pattern]` of `find` command."
    default: '*'
  exclude:
    description: "Exclude patterns of target files. Same as `-not -path [exclude]` of `find` command."
    default: ''
  filter_mode:
    description: "Filtering mode for the reviewdog command [added,diff_context,file,nofilter]."
    default: 'added'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'edit'
  color: 'gray-dark'
