name: 'Run misspell with reviewdog'
description: '🐶 Run misspell with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
  locale:
    description: '-locale flag of misspell. (US/UK)'
    default: ''
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  find_command:
    description: 'A `find` command used to select files for spell checking'
  ignore:
    description: 'Comma-separated words to ignore'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.locale }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
    - $${ inputs.find_command }}
    - ${{ inputs.ignore }}
branding:
  icon: 'edit'
  color: 'gray-dark'
